### ISSUE TITLE
Feature request: Postfix for non JS/TS markup languages like HTML/Svelte markup?

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [ipatalas/vscode-postfix-ts#107]
This extension is `Postfix templates for TypeScript/JavaScript` and maybe I'm getting a bit greedy but I love this extension so much that I kind of want to use it everywhere.

It's already possible by just using postfix in the <script> tag and then moving the lines to the markup but it would be interesting if I could just use postfix directly in the markup.

I saw a related issue that was closed https://github.com/ipatalas/vscode-postfix-ts/issues/46 so maybe this is out of scope but I'm interested if your opinion is the same or has changed.

**Comment by ipatalas** [comment]
> [...] but it would be interesting if I could just use postfix directly in the markup.

Can you show an example of what you mean? If the scenario makes sense for TS/JS developers then I will definitely consider it.

> I saw a related issue that was closed #46 so maybe this is out of scope but I'm interested if your opinion is the same or has changed.

It hasn't changed and I can easily explain why. The core functionality of this extension relies on analyzing TS/JS AST (abstract syntax tree) to be able to provide the completions in a reliable way. This is tied so hard to TS/JS than introducing a new language in the same extension would be a major rework, perhaps even a rewrite from scratch. Quite honestly I don't have time for that as I do that in my spare time.
However I don't mind if someone else picks up the idea and starts its own fork. There are already quite a few postfix-like extensions on the marketplace: https://marketplace.visualstudio.com/search?term=postfix&target=VSCode&category=All%20categories&sortBy=Relevance
Most of them are direct or indirect forks of this extension and I really don't mind. The ones for Python or Go are quite successful so I'm happy this is helping people in their work.

The only exception I can make is for HTML-like languages because this is a big piece of work for all front-end developers, hence recent support for including postfix snippets in TS/JS code embedded in HTML/Svelte/Vue so if you're thinking about something like that then please be more specific, give some examples and let's see :)

**Comment by henrikvilhelmberglund** [comment]
Sure!

For Svelte markup there are blocks that have some special functionality. For example {#each} and {#if}. These examples are from the Svelte docs:

```
<ul>
	{#each items as item}
		<li>{item.name} x {item.qty}</li>
	{/each}
</ul>
```

I think {item.qty} and so on are a bit too specific but having `item.each` that turns into something like the above pattern could be very useful. Wrap everything in an `<ul>` tag, all items in a `<li>` tag and so on.

There are also many different types of data you would loop like this too, regular arrays, objects, fetched data and so on which could have their own postfix entries. Basically if you find yourself using a special pattern a lot you could make it a postfix.

There's also if:

```
{#if porridge.temperature > 100}
	<p>too hot!</p>
{:else if 80 > porridge.temperature}
	<p>too cold!</p>
{:else}
	<p>just right!</p>
{/if}
```

This example is a bit niche but I think postfix would be useful because you could have an if statement based on some state that displays some components if the state is true (for example if the user is logged in), then if the user is not logged in show something else.

You could also have different versions like a postfix complete with all the components already there or a more modular version with the contents of the blocks blank where you can use smaller postfixes with the components you want to use there.

Another thing you could do is just show a certain component with some data. For example I have a component that shows code with Prism highlighting that is called like this
`<ShowCode code={ComponentRaw} name="Component.svelte"/>` 
A postfix for this could add the import statement `import ComponentRaw from "./Component.svelte?raw";` (I would need to move it I guess but that's fine) and then add the above line that fills in the prop values automatically.

One last thing you could do is share postfix templates with your team that are closely related to the thing you're working on.
For example, we have these accessibility responsibilities, we use these tailwind classes in this element/component and create things that would speed the workflow for the whole team and easily share them.

Anyway these are a few things I thought of, there are probably more ways to use this.

**Comment by ipatalas** [comment]
Hi, sorry for the delay but I was pretty busy with real life :) 
Anyway, the idea looks great and I believe this would be super helpful for Svelte developers. 
However that is not a trivial feature because I would need to use a language server for Svelte to be able to parse and analyze its syntax. This is not impossible because one of the main contributors already did that for HTML and it went pretty well but I do have some concerns about it.
First of all I have never used Svelte before so this is not exactly my story and would possibly need some guidance from the community. Svelte syntax seems to be easy so probably not too much to guide but still some extra time. 
Secondly if I do that for Svelte then why not Vue and others? 
How is Svelte better than Vue (or React) and why would I favor it over the others? 
Also front-end world changes so quickly then in few years probably not many will remember it. There's Qwik already around the corner and those front-end libs come and go every few years and trends change quite quickly.
JS and TS will stay though because this is common denominator for all those technologies. That being said I think it's better to start a new extension for Svelte (and others) and plug them in as in micro services world. You use Svelte? Use extension for Svelte, Vue? All right, same story. This was never meant to be a Swiss army knife for postfix templates.
This is also much easier to make a new extension to support Svelte syntax rather than incorporating many different syntaxes into a single extension. Not that it's impossible because it's not true but it's surely extra effort that need to be made to maintain more complexity then.
As long as I like challenges I don't see a place for that in my spare time in any foreseeable future. Sorry but I won't give up so much of my time for that (especially that I'm not even a target user).
As mentioned before I don't mind if someone forks that extension and adapt it for other languages so feel free. I can help in understanding what's the architecture and guiding a bit on how to start, maybe even contributing when it's already working but not necessarily bringing Svelte support here.

**Comment by henrikvilhelmberglund** [comment]
Yeah no problem, it makes a lot of sense. Thanks for explaining your view!

**Comment by ipatalas** [comment]
Thanks for understanding. I hope that wasn't too harsh from my side :) 
I just wanted to explain the reasons instead of just saying no. Life is too short to do everything so we all have to pick our priorities and this is clearly not mine and the effort is just too big for me.
If I could only do OSS work for a living then I'd be happy to develop tools for other developers even for things I don't use but life is life and I have to choose carefully.
