### ISSUE TITLE
hope a new forin

### ISSUE THREAD

**Issue by DebugLyu** [ipatalas/vscode-postfix-ts#111]
forin is vscode keyword
but I always used it behind object, now it has fori and forof 
hope to add a new forin(or another keyword)
thx

ps：english is very pool,hope u can understand

**Comment by ipatalas** [comment]
Hi, I think I get it.
I believe you mean something like this:
![image](https://user-images.githubusercontent.com/2623329/227340760-52e1ac1e-5833-42b6-a4d2-cb16fbdf12b9.png)

For some reason this template was missing since the very beginning. Maybe because I almost never use `forin` loops and nobody requested it so far :) Anyway, it's done and will be released with next version.

**Comment by DebugLyu** [comment]
thx, it's my fault, when I read extension details again, I found I can make the template myself
this extension greatly improve development efficiency
thx again
