### ISSUE TITLE
Disable completions on 0-input

### ISSUE THREAD

**Issue by sweidac** [ipatalas/vscode-postfix-ts#113]
When having an expression ended with the `.`, e.g. `window.` I see only suggestions of postfix completions. I, however, mostly want to explore the opportunity of fields that the expression yields.

Is it feasible to add a setting that disables the completions unil a certain number of characters have been written?

**Comment by ipatalas** [comment]
Interesting because first thing I see are VSCode default completions:
![image](https://github.com/ipatalas/vscode-postfix-ts/assets/2623329/69a5b624-b44c-4ff8-92bf-1f94ecd6eb08)

You can also play around with `editor.snippetSuggestions` setting:
![image](https://github.com/ipatalas/vscode-postfix-ts/assets/2623329/f6e8b5c0-7b3a-4a5c-abf2-b8852ae19a94)

Maybe you have it set to `top`?

**Comment by sweidac** [comment]
You, Sir, just prevented an extension from being uninstalled :)
I didn't think that the completions where acting like snippets, so I probably didn't think of that solution.

Thank you very much!

**Comment by ipatalas** [comment]
Haha, well, it's actually VSCode determining what's the order of items, extensions can only partially influence that. 
I'm glad it helped.
