### ISSUE TITLE
Hope to have better support for other languages

### ISSUE THREAD

**Issue by tiansin** [ipatalas/vscode-postfix-ts#15]
I really like this plugin. At the moment it's great for ts/js languages, but it's not particularly useful for php. I hope to see full support for other languages.thank you.

**Comment by ipatalas** [comment]
Hey,

as the name says it's meant to be used for TS/JS. Never considered adding more languages to it honestly since I'm using vscode only for TS/JS development at the moment. That means I have no interest in spending my time on PHP version which is not a one evening story.
However this is open source so feel free to do it yourself. I can help if needed.
There is a nice parser for PHP: https://www.npmjs.com/package/php-parser
It should do the job. Most of the code would be pretty much reused.
Actually we could even try to enhance this extension so that it's extensible for multiple languages.

**Comment by Alexisvt** [comment]
Hi @ipatalas thank you  first your great work, Im planning to use this for another language, i need to be honest, I never did an extension like this before but I will use your last comment to start the investigation. Mi idea is to try to  use your work for Dart language, so basically what you said is I need to find out or build a parser for Dart and then use the logic that you already did for add new code, Am I right? Thanks

**Comment by ipatalas** [comment]
Hi @Alexisvt,

that's correct. A parser for Dart would be very helpful. It doesn't have to be native in JS if it's not possible, you can still call external code but this will require little more effort.
You can do that all without a parser but that will be more error prone and will also require more effort since you'd have to manually parse strings of Dart code. It's not impossible but a parser makes it all easier.
I would suggest finding one. Writing it from scratch is a long haul project itself.
I can't help much with Dart itself but I can try to assist if you need help in other topics. The extension itself is the easiest part and you could use a lot of my code probably. Hope this helps a bit :)
