### ISSUE TITLE
Add a way to invert `if`/`while` condition

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#81]
Example: `if (a && a && b{not})` it would invert last identifier instead and it seems there is no way to invert whole condition in this case.

As a workaround I'm writing thing like `a > 0.not` at the end to invert an if condition.

WebStorm in example above would suggest multiple variants, however introducing this behavior would be too annoying for existing users, instead I think it can support this:
```ts
if (a && a && b).not {
    ...
}
```

**Comment by ipatalas** [comment]
This was a result of bugfix for #67.
Apparently the fix wasn't perfect. I've redone the fix to apply it only where it makes sense instead of globally and now it's back to old behavior:

![image](https://user-images.githubusercontent.com/2623329/191959323-09d7027e-d9ba-4f16-b881-5a6f2b8a618c.png)

![image](https://user-images.githubusercontent.com/2623329/191959425-2cc37a80-0b04-4dba-ba05-d469eff4b000.png)

That's quite a big and potentially breaking change: https://github.com/ipatalas/vscode-postfix-ts/commit/a126e74e3f201507eef55108fd91cbb74b396a86
Feel free to test it, maybe you can figure out an edge case I did not find :)

**Comment by ipatalas** [comment]
Had a chance to test that? I guess this should no longer be a problem.

**Comment by zardoy** [comment]
> That's quite a big and potentially breaking change: https://github.com/ipatalas/vscode-postfix-ts/commit/a126e74e3f201507eef55108fd91cbb74b396a86

I thought this commit closed it
