### ISSUE TITLE
First class Vue, HTML & Svelte support

### ISSUE THREAD

**Issue by zardoy** [ipatalas/vscode-postfix-ts#96]
Vue becoming very popular in our days. In most cases it used to work (until I requested to not display postfixes in JSX text). Now we need manually handle displaying postfixes in:

1) In <script> (as it's content is treated as JSXText)
2) In attribute interpolations: for Vue it's starting with `:` or `v-` (eg `:data` or `v-if`) in html with `on`. This support might be extremely useful for postfixes like `.not` or `.arg`

Template interpolations in these langs are compatible with JSX.

Attributes in svelte are mostly the same as in JSX.

Support for Svelte and HTML would be just easy to add as it's the same as for Vue.

I implemented all this on next branch (mostly here):

https://github.com/ipatalas/vscode-postfix-ts/commit/aaff6328747400a7c40d1b4bd9f6be340f740769

Again, it's probably not something that this extension should care of, but:

1) it's really easy to support. It's only syntax-handling so we need to implement it once
2) this languages are big part of JS ecosystem and extremely popular

A bit more of my implementation: I'm replacing every single character except new lines. Why? 

https://code.visualstudio.com/api/language-extensions/embedded-languages#language-services-sample

**Comment by ipatalas** [comment]
That's great, any chance you can create a separate PR from commits introducing this? It will be easier to go through all those features one by one rather than a single big PR with couple of new features.

**Comment by zardoy** [comment]
> That's great, any chance you can create a separate PR from commits introducing this? It will be easier to go through all those features one by one rather than a single big PR with couple of new features.

Yes, of course I didn't expect you to merge this PR. Especially for this one to support would be enough to just cherry-pick a few commits. And ok, I will try to open a PR within a few hours. (I'm just currently on mobile)

**Comment by zardoy** [comment]
Sorry, I currently don't know when I'll be home to do this, if you really want, you can cherrypick it from two commits (that I referenced and the last one). However in current implementation null indicates invalid position and undefined that parsing should be done on source code without modifications.

**Comment by henrikvilhelmberglund** [comment]
Any update on this? I can't get postfix to work in <script> tags in .svelte files at all.
Edit: I made a fork of zardoy's fork and next branch, seems to work. 👼

**Comment by zardoy** [comment]
@henrikvilhelmberglund Yes, I made it work a long time ago and published in [TS/JS postfix 2](https://marketplace.visualstudio.com/items?itemName=zardoy.postfix-ts). The only reason is why these changes are not in this repo is because I haven't figured out how to split https://github.com/ipatalas/vscode-postfix-ts/pull/95#issuecomment-1295963091 across PRs (maybe you can help with it ;) Btw I also had plans to do even even more in this fork. For example locally I rewrited it to TS plugin so you can specify assignable types to groups or some specific postfixes, if you want I can published them as well :)

```json
{
    "name": "join",
    "description": "",
    "body": "path.join({{expr}}, $1)",
    "assignableType": "string",
    "when": [
        "identifier",
        "literal"
    ]
}
```

```ts
'./file'.join //or
const p = './file'
p.join
```

**Comment by ipatalas** [comment]
All right, last time I remember I had some issues with cherry picking those commits you pointed and that was true because you had quite a few other commits before those two and because of those change our codebases were on longer compatible hence I couldn't cherry pick them (git couldn't handle it).

Today I gave it another chance, same results but this time I went with the changes the hard way (manually, one by one).
I managed to manually apply changes from: https://github.com/zardoy/vscode-postfix-ts/commit/aaff6328747400a7c40d1b4bd9f6be340f740769, https://github.com/zardoy/vscode-postfix-ts/commit/108085e41a8c436d8d10670e88902c0462cc3019 and also had to apply this too: https://github.com/zardoy/vscode-postfix-ts/commit/d5233e70f7a1bbe3fce8b64ae53d3237467fb94e

It seems like it's working just fine:

1. Svelte
![image](https://user-images.githubusercontent.com/2623329/213885459-4103ae20-6f9c-4c8d-a626-661b8403a1b8.png)
2. Vue
![image](https://user-images.githubusercontent.com/2623329/213885488-e761019d-8ac5-4310-a8bd-bef65347a816.png)
3. HTML
![image](https://user-images.githubusercontent.com/2623329/213885589-8f8ff6a2-6087-4a57-bff7-c9bd6b05abe5.png)


@zardoy if you have time please have a look for any edge cases you found while developing that to see if it works fine: https://github.com/ipatalas/vscode-postfix-ts/tree/svelte-vue-html

For me it looks good and even if not everything works then I think it's still much better :)

If everything is alright I'll release that soon hopefully. Before that I'd like to cherry pick few other changes of yours which I really liked looking at the commits on your `next` branch (https://github.com/zardoy/vscode-postfix-ts/commit/0cec042c18d6bbe3b1986daf5caebcaabfec65a8 this for starters). Not sure if it will be possible to apply them by git so in worst case I'll apply them manually.

**Comment by zardoy** [comment]
Sorry for delay once again, have limited time for now.
> All right, last time I remember I had some issues with cherry picking those commits you pointed and that was true because you had quite a few other commits before those two and because of those change our codebases were on longer compatible hence I couldn't cherry pick them (git couldn't handle it).

Thats weird and surprising to me, didn't know it. I also remember I wanted to do interactive rebase to squash some commits but forgot to do this...

And yes, I've looked into PR, and it looks good. Also thank you so much for taking a look at tests, I remember last time when I looked at tests just a few of them were green.. Really happy to see more changes coming from my `next` branch!

By the way, I tried to compare it https://github.com/ipatalas/vscode-postfix-ts/compare/svelte-vue-html...zardoy:vscode-postfix-ts:next, but it seems GH shows changed files incorrectly. I will look into my branch once again tomorrow.

**Comment by ipatalas** [comment]
> Sorry for delay once again, have limited time for now.

Don't worry, I should be the one to say sorry because I went radio silent for few months :)

> And yes, I've looked into PR, and it looks good. Also thank you so much for taking a look at tests, I remember last time when I looked at tests just a few of them were green.. Really happy to see more changes coming from my `next` branch!

All green locally but now there's always one which randomly fails on GH Actions 🤷🏻‍♂️ 

Update: it turns out it was failing quite consistently but finally I made it :)

I'll leave this issue open until new version is released (most likely this week).

**Comment by ipatalas** [comment]
Ok, all fires extinguished and new version released so closing this.
